export const signatories = [
  {
    name: "John E. Woods",
    title: "UChicago Emeritus Professor of History",
    badge: "UChicago Emeritus Professor",
    badgeType: "emphasized",
  },
  {
    name: "David Martinez",
    title: "UChicago Associate Professor",
    badge: "UChicago Faculty",
    badgeType: "emphasized",
  },
  {
    name: "Jonathan Hall",
    title: "Phyllis Fay Horton Distinguished Service Professor in the Humanities",
    badge: "UChicago Faculty",
    badgeType: "emphasized",
  },
  {
    name: "Edward L. Shaughnessy",
    title: "UChicago Creel Distinguished Service Professor of Early China",
    badge: "UChicago Faculty",
    badgeType: "emphasized",
  },
  {
    name: "Sarah Nooter",
    title: "Edward Olson Professor of Classics at the University of Chicago",
    badge: "UChicago Faculty",
    badgeType: "emphasized",
  },
  {
    name: "Jonah Radding",
    title: "UChicago Assistant Instructional Professor",
    badge: "UChicago Faculty",
    badgeType: "emphasized",
  },
  {
    name: "Emily Austin",
    title: "UChicago Associate Professor",
    badge: "UChicago Faculty",
    badgeType: "emphasized",
  },
  {
    name: "William Levine",
    title: "UChicago Collegiate Assistant Professor",
    badge: "UChicago Faculty",
    badgeType: "emphasized",
  },
  {
    name: "Andrew Ollett",
    title: "UChicago Associate Professor",
    badge: "UChicago Faculty",
    badgeType: "emphasized",
  },
  {
    name: "Eduardo García-Molina",
    title: "Assistant Professor of Classics, University of Illinois Urbana-Champaign",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Rebecca Posner-Hess",
    title: "Phd Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Jonathan Kim",
    title: "University of Chicago J.D Candidate",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Caroline Kaminsky",
    title: "Graduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Ziyu Feng",
    title: "Graduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Theo Knights",
    title: "Univeristy of Chicago, PhD Student, MES and History",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Andreas Petrou-Zeniou",
    title: "PhD Student at MIT",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Evan Yamaguchi",
    title: "Graduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Frances Mangina",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Aydan Shahdadpuri",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Aware Deshmukh",
    title: "Graduate Student at Columbia University",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Ye Ram Kim",
    title: "Graduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Feifan Li",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alejandro Sarria",
    title: "PhD Student at Duke University",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Brynna Gang",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Parker T. Robbins",
    title: "PhD Student in Linguistics at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Nathan Katkin",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Ye Ram Kim",
    title: "Graduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alicia Badea",
    title: "PhD Student in Germanic Studies at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Arshy Azizi",
    title: "University of Chicago, PhD Candidate, Classics",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alexandra Ware",
    title: "Graduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Zhicong Liu",
    title: "J.D. Candidate at University of Pennsylvania",
  },
  {
    name: "Adam Katwan",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Michael Powell",
    title: "University of Chicago Doctoral Candidate",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Nora Hartzell",
    title: "PhD student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Emily Shein",
    title: "Graduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Braeden Giaconi",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Michael Wayne",
    title: "PhD Student in History, Yale GSAS",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "John Marvin",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Suin Choi",
    title: "Graduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Jack Fantini",
    title: "PhD Candidate at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Abhiraj Singh",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Gray Reichl",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Yuanlong Zheng",
    title: "University of Chicago, PhD student, Undergraduate Alum, 2024",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Jacob McDowell",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Martin Niederl",
    title: "PhD Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "G Rowan",
    title: "Graduate Student",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "William Robertson",
    title: "Master's Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Livia Zhu",
    title: "Masters Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Henie Zhang",
    title: "UChicago Master's Student",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Heather Liu",
    title: "Univeristy of Chicago Parent",
    badge: "UChicago Parent",
    badgeType: "normal",
  },
  {
    name: "Blaise Antin",
    title: "Univeristy of Chicago Parent",
    badge: "UChicago Parent",
    badgeType: "normal",
  },
  {
    name: "Isabelle Lee",
    title: "BA/MA Candidate at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Zephaniah Roe",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Antônio Both Schenatto",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Smyrna Osae",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Grace Donavan Lafuente",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alice Wang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Madison Mathes",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Vanessa Vaz",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Surya Chinnappa",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Avery Winder",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Eliot Aguera y Arcas",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Elizabeth Harrison",
    title: "University of Chicago, English, Classics and Comparative Literature BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Taylor Pate",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Iris chen",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Stella Jiang",
    title: "University of Chicago, BS, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Mariska Kassi",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Sarah Ware",
    title: "Unversity of Chicago, Classical Studies and Medieval Studies AB, 2024",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Ashley Kulp",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Elizabeth Johnson",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alexa Shepherd",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Josephine Barboriak",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Will Zimmermann",
    title: "University of Chicago, BA in Linguistics, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Ryan MacIsaac",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Christine Hignite",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Theo Johnson",
    title: "University of Chicago, BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Emma Beane",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Mickey Kelly",
    title: "University of Chicago, BA Physics, 2024",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Mansoor Johnson",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Daniel Boscu",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Yuning Shu",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Brisa Mar Peralta",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Katherine Li",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alexander Gomez",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Sasha Maskoff",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Barbara Marbell",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Will Epstein",
    title: "University of Chicago, BS, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Carolina Sardinas",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Chester Wooldridge",
    title: "University of Chicago, Biology BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Cole Washburn",
    title: "Univeristy of Chicago, Bachelors of English, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Yujini Son",
    title: "University of Chicago, BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Kayla Davis",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Selah Dungey",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Don Harmon",
    title: "University of Chicago, BA Classics and Comparative Literature, 2022",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "J.C. Rodríguez Oceguera",
    title: "University of Chicago, Race, Diaspora, and Indigeneity, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Julia Marin",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Hayley Mirabile",
    title: "University of Chicago, Public Policy Studies BA, 2023",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Will Choi",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Asad Fayiz",
    title: "BS/MS Candidate at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Elliot Lin",
    title: "University of Chicago, 2024 and University of Chicago MAPSS-Econ, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Mack Minter",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Kait Albarran",
    title: "Unviersity of Chicago, Biological Chemistry BS, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Violet Reed",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Oscar Dorr",
    title: "University of Chicago, BA, 2024",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Rebecca Shaw",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alyssa Manthi",
    title: "BA/MA Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alan Cano",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "India Hill",
    title: "University of Chicago, Critical Race & Ethnic Studies BA, 2024",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Georgia Levine",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Kaleel Mayanja",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Agustin Esteva",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Lloali Gallegos",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Eve Glasergreen",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Violeta Lopez Molina",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Kali Konstantinakos",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Andrew Manuel Soto",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Ovia Sundar",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Gianfranco Miranda Romero",
    title: "University of Chicago, BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Otto Reed",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Xiaoqi Zhou",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Annie Yang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Shama Tirukkala",
    title: "University of Chicago, BA, 2024",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Maxime Zigrand",
    title: "University of Chicago, MA Political Science, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Mingxuan (Aldous) Li",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Sophia Wang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Nora Sampson",
    title: "University of Chicago, Biological Chemistry & Chemistry BS, 2024",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Leo Kohlhepp",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Jack Kozlowski",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Gabriela Fernandez",
    title: "BA/MA Candidate at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Jordyn Smith",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Cynthia Wang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Sanaiya M. Luthar",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Zvi Gomez Fisher",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Lee Gutman",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Addison Marshall",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Isabella Ahuactzin",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Noah Springhorn",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Carly Ryan Cairns",
    title: "University of Chicago Political Science and Human Rights BA, Social Sciences MA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Stella Firmenich",
    title: "University of Chicago Student",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Seri Welsh",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "William Anderson",
    title: "Undergraduate Student, University of Wisconsin-Madison",
    badge: null,
  },
  {
    name: "Mae Daughety",
    title: "Undergraduate at Texas State University",
    badge: null,
  },
  {
    name: "Sydney Cook",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Chloe Chiles Troutman",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Rohan Rao",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Soph Franklin",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Natalie Antin",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Maximiliano Mendoza",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Hannah Thier",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Anjali Jain",
    title: "Incoming Master of Arts Program in the Humanities",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Owen Sussman",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Yufei Chen",
    title: "BA/MA Candidate at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Charles Robinson",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Francesco Rahe",
    title: "BA in Fundamentals: Issues and Texts and Religious Studies, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Viviana Hilario",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Abbey Figueroa",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Marcus Catanzaro",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Tuba Balta",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Leslie Xiao",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Viviana Ornelas",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Emma Pavlicek",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Jacob Stump",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Harjas Sandhu",
    title: "University of Chicago, BA in Physics, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Monica Gould",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Jack Foley",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Clara Pressey",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Ximena Valverde",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Julia Fink",
    title: "University of Chicago, Classical Studies, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Desmond Saunders",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Nic Restivo",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Madeleine Grosso",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Sallie Hinkle",
    title: "University of Chicago, Global Studies BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Jenna Moor",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Keyara Sims",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Zoe Fulton",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Mira Kaplan",
    title: "University of Chicago, Philosophy BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Nicole Reed",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Julian Huang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Katherine O’Donnell",
    title: "University of Chicago, BS, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Eva Youel Page",
    title: "University of Chicago, Comparative Human Development BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Esslam Ashour",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Gabriela Hernandez",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Grayson Maki",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Soraya Wilson",
    title: "University of Chicago, BA/MA Candidate",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Pavlik Braverman",
    title: "Univeristy of Chicago Undergraduate / Harris School of Public Policy",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Sydney Sparr",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Walton Yan",
    title: "University of Chicago, Classics, German, Art History, and Religious Studies BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Lillian Fu",
    title: "UChicago Student",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Marina Mendoza",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alexa Perez",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Ashlee Boodoo",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Declan Hilfers",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Katia Sergeeva",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Pritish Das",
    title: "University of Chicago, MAPSS, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Vivi McDermott",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Corinne de Syon",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Erin Meehan",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Oscar Xing",
    title: "Alumni of the Social Sciences Division",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Lucille Cygal",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Madeline Chaffer",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },

  {
    name: "Audrey Shin",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Kaavya Agarwal",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Nicholas Cipi",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Adelle Almansi",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "David Jercha",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Linden Martin",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Alexis Elliott",
    title: "University of Chicago, Computer Science BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Cameron Clark",
    title: "Univeristy of Chicago, Classical Studies BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Angharad A. Whitfield",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Hanzhi Wang",
    title: "University of Chicago Class of 2022",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Aine Zhang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Yanyu Hu",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Xiru Du",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Steven Wang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Rosalyn Jia",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Olivia Moreno",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Brooklyn Zhao",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Aaron Huang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Sasha Malysheva",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  // {
  //   name: "Ariana L",
  //   title: "Undergraduate Student at the University of Chicago",
  //   badge: "UChicago Student",
  //   badgeType: "normal",
  // },
  {
    name: "Rohan Buluswar",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Vincent Tran",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Aaron Yang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Ariana L",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Liam Horton",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Junze Bao",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Xueqi Sun",
    title: "Undergraduate and Graduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Mido Sang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Ruotian Wang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Dominique Marichal",
    title: "University of Chicago, Biological Sciences BA, 2021",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Linchi Zhang",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Marcus Kuo",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Arwen Bare",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Isabel Villalobos",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Madeline Brown",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Katherine Olivares Guzman",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Nicolas Garcia",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Kyle Lin",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Kaiyang Chen",
    title: "University of Chicago, Philosophy and Religious Studies BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Beckett Pryor",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Huyen-Anh Giang",
    title: "University of Chicago, BA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Julian McCoy",
    title: "University of Chicago, MA, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Cooper Komatsu",
    title: "University of Chicago AB/AM 2024",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Abigail Poag",
    title:
      "University of Chicago, BA in Comparative Literature and Russian and East European Studies, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Frances Poth",
    title: "University of Chicago, Economics, 2024",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Ravindra Mangar",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Ethan Moore",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Leon Gold",
    title: "University of Chicago, Physics and Geophysical Sciences, 2025",
    badge: "UChicago Graduate",
    badgeType: "normal",
  },
  {
    name: "Felix Farb",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Ashley Campos",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Josh Johnson",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Onese Ewherido",
    title: "Undergraduate Student at the University of Chicago",
    badge: "UChicago Student",
    badgeType: "normal",
  },
  {
    name: "Riley Rosener",
    badge: null,
  },
  {
    name: "Lydia Liu",
    badge: null,
  },
  {
    name: "Anton Lesokhin",
    badge: null,
  },
  {
    name: "Campbell Rosener",
    badge: null,
  },
  {
    name: "Aileen Chuchuca",
    badge: null,
  },
  {
    name: "Charlie Ader",
    badge: null,
  },
  {
    name: "Oluwaseyi Christopher Kadiri",
    badge: null,
  },
  {
    name: "Kalea Walthall",
    badge: null,
  },
  {
    name: "Breland Bach",
    badge: null,
  },
  {
    name: "Celeste Taylor",
    badge: null,
  },
  {
    name: "JJ Robeck",
    badge: null,
  },
  {
    name: "Weston Fox",
    badge: null,
  },
  {
    name: "Celina Cortes",
    badge: null,
  },
  {
    name: "Legrand Davis",
    badge: null,
  },
  {
    name: "Marissa Todd",
    badge: null,
  },
  // {
  //   name: "Leena",
  //   badge: null,
  // },
  {
    name: "Alex Hasapis",
    badge: null,
  },
  {
    name: "Kailas Devulapally",
    badge: null,
  },
  {
    name: "Egheosase Odiase",
    badge: null,
  },
  {
    name: "Emily Siwing Xia",
    badge: null,
  },
  // {
  //   name: "Rachel W",
  //   title: "University of Chicago, BA, 2024",
  //   badge: "UChicago Graduate",
  //   badgeType: "normal",
  // },
  // {
  //   name: "Kayla",
  //   title: "Undergraduate Student at the University of Chicago",
  //   badge: "UChicago Student",
  //   badgeType: "normal",
  // },
  {
    name: "Nicole Faigen",
    badge: null,
  },
  // {
  //   name: "Jo",
  //   title: "Undergraduate Student at the University of Chicago",
  //   badge: "UChicago Student",
  //   badgeType: "normal",
  // },
  // {
  //   name: "Sophie",
  //   title: "Kings College London Alumni",
  //   badge: null,
  // },
  // {
  //   name: "Mia",
  //   title: "Undergraduate Student at the University of Chicago",
  //   badge: "UChicago Student",
  //   badgeType: "normal",
  // },
  // {
  //   name: "Anna",
  //   title: "Undergraduate Student at the University of Chicago",
  //   badge: "UChicago Student",
  //   badgeType: "normal",
  // },
];
